USE lab4;
GO

SELECT AUDITORIUM.AUDITORIUM[Номер аудитории], AUDITORIUM_TYPE.AUDITORIUM_TYPENAME[Имя с компьютером]
FROM AUDITORIUM INNER JOIN AUDITORIUM_TYPE
ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE 
AND AUDITORIUM_TYPE.AUDITORIUM_TYPENAME LIKE '%комп%'