USE lab4
GO

SELECT DISTINCT PROGRESS.NOTE[Оценка], STUDENT.NAME[Имя студента],
		SUBJECT.SUBJECT[Дисциплина], PULPIT.PULPIT[Кафедра], FACULTY.FACULTY[Факультет],
CASE 
WHEN(PROGRESS.NOTE = 6) THEN 'шесть'
WHEN(PROGRESS.NOTE = 7) THEN 'семь'
WHEN(PROGRESS.NOTE = 8) THEN 'восемь'
ELSE 'не 6, 7 или 8'
END [ПРИМЕЧАНИЕ]

FROM PROGRESS
INNER JOIN STUDENT ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
INNER JOIN SUBJECT ON PROGRESS.SUBJECT = SUBJECT.SUBJECT
INNER JOIN PULPIT ON SUBJECT.PULPIT = PULPIT.PULPIT
INNER JOIN FACULTY ON FACULTY.FACULTY = PULPIT.FACULTY
INNER JOIN PROFESSION ON PROFESSION.FACULTY = FACULTY.FACULTY

WHERE PROGRESS.NOTE BETWEEN 6 AND 8
ORDER BY PROGRESS.NOTE DESC;

SELECT * FROM PROGRESS;
