USE lab4
GO

SELECT PULPIT_NAME
FROM PULPIT
WHERE FACULTY IN (SELECT FACULTY
					FROM PROFESSION
					WHERE (PROFESSION_NAME LIKE '%технология%')
							OR (PROFESSION_NAME LIKE '%технологии%'))

SELECT PULPIT_NAME
FROM PULPIT P
INNER JOIN (
	SELECT DISTINCT FACULTY
	FROM PROFESSION 
		WHERE (PROFESSION_NAME LIKE '%технология%')
				OR (PROFESSION_NAME LIKE '%технологии%')
) AS PR ON PR.FACULTY = P.FACULTY


SELECT DISTINCT PULPIT_NAME
FROM PULPIT P
INNER JOIN FACULTY F ON P.FACULTY = F.FACULTY
INNER JOIN PROFESSION PR ON F.FACULTY = PR.FACULTY
WHERE (PROFESSION_NAME LIKE '%технология%')
		OR (PROFESSION_NAME LIKE '%технологии%')
