USE lab4
GO

SELECT 
    (SELECT AVG(NOTE) FROM PROGRESS WHERE SUBJECT = 'нюХо') [avg_OAiP],
    (SELECT AVG(NOTE) FROM PROGRESS WHERE SUBJECT = 'ад') [avg_BD],
    (SELECT AVG(NOTE) FROM PROGRESS WHERE SUBJECT = 'ясад') [avg_SUBD]