USE lab4
GO 

SELECT  AUDITORIUM_NAME, AUDITORIUM_TYPE, AUDITORIUM_CAPACITY
FROM AUDITORIUM A1
	WHERE A1.AUDITORIUM_CAPACITY = 
	(
		SELECT TOP 1 A2.AUDITORIUM_CAPACITY
		FROM AUDITORIUM A2
			WHERE A2.AUDITORIUM_TYPE = A1.AUDITORIUM_TYPE
			ORDER BY A2.AUDITORIUM_CAPACITY DESC
	)
			ORDER BY A1.AUDITORIUM_CAPACITY DESC