USE lab4
GO

---Задание 1---

SELECT AT.AUDITORIUM_TYPE,
	   MAX(A.AUDITORIUM_CAPACITY) AS Max_Capacity,
	   MIN(A.AUDITORIUM_CAPACITY) AS Min_Capacity,
	   AVG(A.AUDITORIUM_CAPACITY) AS Avg_Capacity,
	   SUM(A.AUDITORIUM_CAPACITY) AS Sum_Capacity,
	   COUNT(*) AS Count_Auditorium
FROM AUDITORIUM A INNER JOIN AUDITORIUM_TYPE AT
	ON A.AUDITORIUM_TYPE = AT.AUDITORIUM_TYPE
	GROUP BY AT.AUDITORIUM_TYPE

---Заднаие 2---

SELECT *
FROM (SELECT CASE 
		WHEN PROGRESS.NOTE BETWEEN 1 AND 5 THEN 'Оценка ниже 5'
		WHEN  PROGRESS.NOTE BETWEEN 5 AND 7 THEN 'Оценка от 5 до 7'
	    ELSE 'Оценка выше 7'
	    END [Пределы оценок], count(*)[Количество]
FROM PROGRESS GROUP BY CASE
	WHEN PROGRESS.NOTE BETWEEN 1 AND 5 THEN 'Оценка ниже 5'
	WHEN PROGRESS.NOTE BETWEEN 5 AND 7 THEN 'Оценка от 5 до 7'
	ELSE 'Оценка выше 7'
	END) AS T
		ORDER BY CASE[Пределы оценок]
			WHEN 'Оценка ниже 5' THEN 3
			WHEN 'Оценка от 5 до 7' THEN 2
			WHEN 'Оценка выше 7' THEN 1
			ELSE 0
		END

---Задание 3---

SELECT f.FACULTY,
	   g.PROFESSION,
	   g.IDGROUP,
	   (2014 - g.YEAR_FIRST) AS 'Курс',
	   ROUND(AVG(CAST(p.NOTE AS FLOAT)),2) AS [Средняя оценка]
FROM FACULTY f 
	INNER JOIN GROUPS g ON f.FACULTY = g.FACULTY
	INNER JOIN STUDENT s ON g.IDGROUP = s.IDGROUP
	INNER JOIN PROGRESS p ON p.IDSTUDENT = s.IDSTUDENT
GROUP BY f.FACULTY, g.PROFESSION, g.IDGROUP, g.YEAR_FIRST
ORDER BY [Средняя оценка] DESC

---Задание 4---

SELECT f.FACULTY,
	   g.PROFESSION,
	   g.IDGROUP,
	   (2014 - g.YEAR_FIRST) AS 'Курс',
	   ROUND(AVG(CAST(p.NOTE AS FLOAT)),2) AS [Средняя оценка]
FROM FACULTY f 
	INNER JOIN GROUPS g ON f.FACULTY = g.FACULTY
	INNER JOIN STUDENT s ON g.IDGROUP = s.IDGROUP
	INNER JOIN PROGRESS p ON p.IDSTUDENT = s.IDSTUDENT
	WHERE p.SUBJECT LIKE 'ОАиП' OR p.SUBJECT LIKE 'БД'
GROUP BY f.FACULTY, g.PROFESSION, g.IDGROUP, g.YEAR_FIRST
ORDER BY [Средняя оценка] DESC

---Задание 5---

SELECT f.FACULTY,
	   p.SUBJECT,
	   g.PROFESSION,
	   ROUND(AVG(CAST(p.NOTE AS FLOAT)),2) AS 'Средняя оценка'
FROM FACULTY f 
INNER JOIN GROUPS g ON f.FACULTY = g.FACULTY
INNER JOIN STUDENT s ON g.IDGROUP = s.IDGROUP
INNER JOIN PROGRESS p ON s.IDSTUDENT = p.IDSTUDENT
	WHERE f.FACULTY LIKE 'ХТиТ'
GROUP BY f.FACULTY, p.SUBJECT, g.PROFESSION

---Задание 6---

SELECT SUBJECT,
	   NOTE,
	   COUNT(NOTE) AS 'Кол-во студенов'
FROM PROGRESS
	GROUP BY SUBJECT, NOTE
		HAVING NOTE = 8 OR NOTE = 9 
ORDER BY SUBJECT
